# Covariance & Corelation

In [1]:
import seaborn as sns

In [2]:
df = sns.load_dataset('healthexp')

In [3]:
df

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

In [4]:
df.head(2)

   Year  Country  Spending_USD  Life_Expectancy
0  1970  Germany       252.311             70.6
1  1970   France       192.143             72.2

# covariance

In [5]:
df.cov(numeric_only=True)

                         Year  Spending_USD  Life_Expectancy
Year               201.098848  2.571883e+04        41.915454
Spending_USD     25718.827373  4.817761e+06      4166.800912
Life_Expectancy     41.915454  4.166801e+03        10.733902

# co-relation

In [6]:
df.corr(numeric_only=True, method= "pearson")

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.826273         0.902175
Spending_USD     0.826273      1.000000         0.579430
Life_Expectancy  0.902175      0.579430         1.000000

In [7]:
df.corr(numeric_only=True, method= "spearman")

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.931598         0.896117
Spending_USD     0.931598      1.000000         0.747407
Life_Expectancy  0.896117      0.747407         1.000000

In [8]:
df =  sns.load_dataset('flights')

In [9]:
df.head(2)

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118

In [10]:
df.corr(numeric_only=True, method= "pearson")

                year  passengers
year        1.000000    0.921824
passengers  0.921824    1.000000

In [11]:
df =  sns.load_dataset('tips')

In [12]:
df.corr(numeric_only=True, method= "spearman")

            total_bill       tip      size
total_bill    1.000000  0.678968  0.604791
tip           0.678968  1.000000  0.468268
size          0.604791  0.468268  1.000000